# Generated by Django 2.1.1 on 2018-09-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Names',
        ),
    ]
