# Generated by Django 2.1.1 on 2018-10-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_loader', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
