# Generated by Django 2.1.1 on 2018-10-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_estimator', '0003_auto_20181002_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill',
            new_name='skills',
        ),
    ]
