# Generated by Django 2.1.1 on 2018-10-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_estimator', '0004_auto_20181002_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataskill', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
