# Generated by Django 2.1.1 on 2018-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_estimator', '0005_dataskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataskill',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
